#!/usr/bin/env python3
"""
Add new products to the Resist N Co database via Prisma.
16 new products: 5 t-shirts, 5 hoodies, 3 tuques, 3 accessories.
"""

import subprocess
import json
import os
import sys

# Product definitions based on real POD supplier catalogs
NEW_PRODUCTS = [
    # ==================== 5 T-SHIRTS ====================
    {
        "name": "T-Shirt « Bye Don »",
        "slug": "tshirt-bye-don",
        "description": "Poing levé rouge tenant une couronne brisée, texte BYE DON. Un message sans ambiguïté: on n'en veut plus. Bella+Canvas 3001, coton peigné 100%, impression DTG.",
        "category": "tshirt",
        "basePrice": 29.99,
        "imageUrl": "/products/tshirt-bye-don.jpg",
        "supplier": "Printful",
        "supplierModel": "Bella+Canvas 3001",
        "supplierCost": 12.95,
        "supplierProductId": "71",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Dark Grey Heather", "hex": "#3a3a3a"},
            {"name": "Maroon", "hex": "#5a1a2a"},
            {"name": "Red", "hex": "#8a1a1a"},
        ],
        "sizes": ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
        "tags": "anti-trump,resistance,meme",
    },
    {
        "name": "T-Shirt « Tiny Hands, Giant Lies »",
        "slug": "tshirt-tiny-hands",
        "description": "Mains dorées tenant un mégaphone, texte TINY HANDS GIANT LIES. La désinformation à l'échelle présidentielle. Gildan 64000 Softstyle, coton ring-spun.",
        "category": "tshirt",
        "basePrice": 27.99,
        "imageUrl": "/products/tshirt-tiny-hands.jpg",
        "supplier": "Printify",
        "supplierModel": "Gildan 64000",
        "supplierCost": 9.95,
        "supplierProductId": "6",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "White", "hex": "#f5f0e8"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Dark Heather", "hex": "#3a3a3a"},
            {"name": "Sport Grey", "hex": "#9a9a9a"},
        ],
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "tags": "anti-trump,satire,disinformation",
    },
    {
        "name": "T-Shirt « Covfefe Resistance Dept. »",
        "slug": "tshirt-covfefe",
        "description": "Tampon officiel rouge COVFEFE - DEPT OF RESISTANCE. Quand un tweet typo devient un mouvement. Comfort Colors 1717, coton ring-spun garment-dyed, toucher vintage.",
        "category": "tshirt",
        "basePrice": 32.99,
        "imageUrl": "/products/tshirt-covfefe.jpg",
        "supplier": "Printful",
        "supplierModel": "Comfort Colors 1717",
        "supplierCost": 15.95,
        "supplierProductId": "1033",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "Pepper", "hex": "#3a3a3a"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Forest", "hex": "#1a3a2a"},
            {"name": "Burgundy", "hex": "#5a1a2a"},
        ],
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "tags": "anti-trump,meme,satire",
    },
    {
        "name": "T-Shirt « Fact Check the Feed »",
        "slug": "tshirt-fact-check",
        "description": "Loupe rouge sur écran de téléphone, texte FACT CHECK THE FEED. La désinformation est une épidémie. Vérifiez avant de partager. Bella+Canvas 3413 Tri-Blend, toucher soyeux.",
        "category": "tshirt",
        "basePrice": 31.99,
        "imageUrl": "/products/tshirt-fact-check.jpg",
        "supplier": "Printify",
        "supplierModel": "Bella+Canvas 3413",
        "supplierCost": 13.50,
        "supplierProductId": "302",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Dark Grey Heather", "hex": "#3a3a3a"},
            {"name": "Maroon", "hex": "#5a1a2a"},
            {"name": "Athletic Heather", "hex": "#8a8a8a"},
        ],
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "tags": "disinformation,media-literacy,resistance",
    },
    {
        "name": "T-Shirt « No Planet B »",
        "slug": "tshirt-no-planet-b",
        "description": "Planète Terre protégée par des mains, texte NO PLANET B. Il n'y a pas de planète de rechange. Bella+Canvas 3001ECO, coton recyclé, écologique.",
        "category": "tshirt",
        "basePrice": 29.99,
        "imageUrl": "/products/tshirt-no-planet-b.jpg",
        "supplier": "Printify",
        "supplierModel": "Bella+Canvas 3001ECO",
        "supplierCost": 14.50,
        "supplierProductId": "471",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "Heather Forest", "hex": "#1a3a2a"},
            {"name": "Dark Grey Heather", "hex": "#3a3a3a"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Athletic Heather", "hex": "#8a8a8a"},
        ],
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "tags": "ecologie,climat,action",
    },

    # ==================== 5 HOODIES ====================
    {
        "name": "Hoodie « No Kings, No Con Men »",
        "slug": "hoodie-no-kings",
        "description": "Couronne renversée en flammes, texte NO KINGS NO CON MEN. L'Amérique n'est pas une monarchie. Gildan 18500 Heavy Blend, 50/50 coton-polyester, capuche ajustable.",
        "category": "hoodie",
        "basePrice": 54.99,
        "imageUrl": "/products/hoodie-no-kings.jpg",
        "supplier": "Printify",
        "supplierModel": "Gildan 18500",
        "supplierCost": 21.58,
        "supplierProductId": "77",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Maroon", "hex": "#5a1a2a"},
            {"name": "Dark Heather", "hex": "#3a3a3a"},
            {"name": "Sport Grey", "hex": "#9a9a9a"},
        ],
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "tags": "anti-trump,resistance,democratie",
    },
    {
        "name": "Hoodie « Grift Alert »",
        "slug": "hoodie-grift-alert",
        "description": "Alarme rouge avec signe dollar, texte GRIFT ALERT - FOLLOW THE MONEY. Suivez l'argent, toujours. Bella+Canvas 3719, premium, coton peigné.",
        "category": "hoodie",
        "basePrice": 59.99,
        "imageUrl": "/products/hoodie-grift-alert.jpg",
        "supplier": "Printful",
        "supplierModel": "Bella+Canvas 3719",
        "supplierCost": 25.95,
        "supplierProductId": "173",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Maroon", "hex": "#5a1a2a"},
            {"name": "Dark Grey Heather", "hex": "#3a3a3a"},
            {"name": "Forest", "hex": "#1a3a2a"},
        ],
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "tags": "anti-trump,corruption,satire",
    },
    {
        "name": "Hoodie « Not My Circus »",
        "slug": "hoodie-not-my-circus",
        "description": "Masque de clown doré barré, texte NOT MY CIRCUS NOT MY CLOWN. Le cirque présidentaire est annulé. Gildan 18500, capuche doublée, poche kangourou.",
        "category": "hoodie",
        "basePrice": 54.99,
        "imageUrl": "/products/hoodie-not-my-circus.jpg",
        "supplier": "Printify",
        "supplierModel": "Gildan 18500",
        "supplierCost": 21.58,
        "supplierProductId": "77",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Dark Heather", "hex": "#3a3a3a"},
            {"name": "Maroon", "hex": "#5a1a2a"},
            {"name": "Sport Grey", "hex": "#9a9a9a"},
        ],
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "tags": "anti-trump,satire,resistance",
    },
    {
        "name": "Hoodie « Keep Oil in the Ground »",
        "slug": "hoodie-keep-oil-ground",
        "description": "Pipeline barré avec racines d'arbres, texte KEEP OIL IN THE GROUND. L'industrie pétrolière est le problème, pas la solution. Bella+Canvas 3719, premium.",
        "category": "hoodie",
        "basePrice": 59.99,
        "imageUrl": "/products/hoodie-keep-oil-ground.jpg",
        "supplier": "Printful",
        "supplierModel": "Bella+Canvas 3719",
        "supplierCost": 25.95,
        "supplierProductId": "173",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "Heather Forest", "hex": "#1a3a2a"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Dark Grey Heather", "hex": "#3a3a3a"},
            {"name": "Maroon", "hex": "#5a1a2a"},
        ],
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "tags": "ecologie,petrole,climat",
    },
    {
        "name": "Hoodie « Memes Aren't Evidence »",
        "slug": "hoodie-memes-evidence",
        "description": "Cerveau mécanique en engrenages, texte MEMES ≠ EVIDENCE. Un meme n'est pas une source. Pensez critiques. Gildan 18600 Full-Zip, capuche zippée.",
        "category": "hoodie",
        "basePrice": 57.99,
        "imageUrl": "/products/hoodie-memes-evidence.jpg",
        "supplier": "Printify",
        "supplierModel": "Gildan 18600",
        "supplierCost": 24.50,
        "supplierProductId": "129",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Dark Heather", "hex": "#3a3a3a"},
            {"name": "Sport Grey", "hex": "#9a9a9a"},
            {"name": "Maroon", "hex": "#5a1a2a"},
        ],
        "sizes": ["S", "M", "L", "XL", "2XL", "3XL"],
        "tags": "disinformation,media-literacy,critical-thinking",
    },

    # ==================== 3 TUQUES ====================
    {
        "name": "Tuque « Truth Matters »",
        "slug": "tuque-truth-matters",
        "description": "Balance penchée vers la vérité, texte TRUTH MATTERS. Les mensonges tuent la démocratie. Tuque tricot 100% acrylique, doublure polaire, rebord rabattu.",
        "category": "accessory",
        "basePrice": 24.99,
        "imageUrl": "/products/tuque-truth-matters.jpg",
        "supplier": "Printful",
        "supplierModel": "Cuffed Knit Beanie",
        "supplierCost": 12.95,
        "supplierProductId": "284",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Dark Grey", "hex": "#3a3a3a"},
            {"name": "Maroon", "hex": "#5a1a2a"},
            {"name": "Red", "hex": "#8a1a1a"},
        ],
        "sizes": ["Unique"],
        "tags": "disinformation,truth,democratie",
    },
    {
        "name": "Tuque « Question Everything »",
        "slug": "tuque-question-everything",
        "description": "Point d'interrogation en flèches entremêlées, texte QUESTION EVERYTHING. Vérifiez, recoupez, décidez. Tuque trikt 100% acrylique.",
        "category": "accessory",
        "basePrice": 22.99,
        "imageUrl": "/products/tuque-question-everything.jpg",
        "supplier": "Printify",
        "supplierModel": "Cuffed Knit Beanie",
        "supplierCost": 10.50,
        "supplierProductId": "425",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Dark Grey", "hex": "#3a3a3a"},
            {"name": "Maroon", "hex": "#5a1a2a"},
        ],
        "sizes": ["Unique"],
        "tags": "disinformation,critical-thinking,resistance",
    },
    {
        "name": "Tuque « Resist Every Day »",
        "slug": "tuque-resist-every-day",
        "description": "Poing levé avec pousse verte, texte RESIST EVERY DAY. La résistance est quotidienne. Tuque tricot 100% acrylique, doublure polaire.",
        "category": "accessory",
        "basePrice": 24.99,
        "imageUrl": "/products/tuque-resist-every-day.jpg",
        "supplier": "Gooten",
        "supplierModel": "Cuffed Knit Beanie",
        "supplierCost": 11.25,
        "supplierProductId": "gooten_beanie_001",
        "colors": [
            {"name": "Black", "hex": "#1a1a1a"},
            {"name": "Navy", "hex": "#1a2b4a"},
            {"name": "Dark Grey", "hex": "#3a3a3a"},
            {"name": "Maroon", "hex": "#5a1a2a"},
            {"name": "Forest Green", "hex": "#1a3a2a"},
        ],
        "sizes": ["Unique"],
        "tags": "resistance,ecologie,action",
    },

    # ==================== 3 ACCESSOIRES ====================
    {
        "name": "Tasse « Resist Every Day »",
        "slug": "mug-resist-every-day",
        "description": "Poing levé avec pousse verte, texte RESIST EVERY DAY. Le café du matin pour commencer une journée de résistance. Mug céramique 11oz, émail premium, compatible lave-vaisselle.",
        "category": "accessory",
        "basePrice": 16.99,
        "imageUrl": "/products/mug-resist-every-day.jpg",
        "supplier": "Printful",
        "supplierModel": "White Glossy Mug 11oz",
        "supplierCost": 7.95,
        "supplierProductId": "925",
        "colors": [
            {"name": "White", "hex": "#f5f0e8"},
            {"name": "Black", "hex": "#1a1a1a"},
        ],
        "sizes": ["11oz"],
        "tags": "resistance,ecologie,quotidien",
    },
    {
        "name": "Sous-verre « Organize Mobilize »",
        "slug": "coaster-organize-mobilize",
        "description": "Mains jointes en cercle, texte ORGANIZE MOBILIZE - SOLIDARITY. Organisez-vous, mobilisez-vous, solidaires. Liège naturel, diamètre 10cm, résistant à l'eau.",
        "category": "accessory",
        "basePrice": 14.99,
        "imageUrl": "/products/coaster-organize-mobilize.jpg",
        "supplier": "Printify",
        "supplierModel": "Cork-Backed Coaster",
        "supplierCost": 3.50,
        "supplierProductId": "coaster_cork",
        "colors": [
            {"name": "Natural Cork", "hex": "#c4a882"},
            {"name": "Black", "hex": "#1a1a1a"},
        ],
        "sizes": ["Set de 4"],
        "tags": "resistance,solidarite,organisation",
    },
    {
        "name": "Sac-tote « No Planet B »",
        "slug": "tote-no-planet-b",
        "description": "Planète Terre protégée par des mains, texte NO PLANET B. Sac-tote écologique en coton recyclé. Remplacez les sacs plastiques, portez le message partout.",
        "category": "accessory",
        "basePrice": 19.99,
        "imageUrl": "/products/tote-no-planet-b.jpg",
        "supplier": "Printful",
        "supplierModel": "Eco Tote Bag EC8000",
        "supplierCost": 8.95,
        "supplierProductId": "1078",
        "colors": [
            {"name": "Natural", "hex": "#c4a882"},
            {"name": "Black", "hex": "#1a1a1a"},
        ],
        "sizes": ["Unique"],
        "tags": "ecologie,climat,reutilisable",
    },
]

# Generate the TypeScript seed addition
def generate_ts():
    products_ts = ""
    for p in NEW_PRODUCTS:
        colors_ts = ", ".join([f'{{ name: "{c["name"]}", hex: "{c["hex"]}" }}' for c in p["colors"]])
        sizes_ts = ", ".join([f'"{s}"' for s in p["sizes"]])
        products_ts += f"""  {{
    name: "{p["name"]}",
    slug: "{p["slug"]}",
    description: "{p["description"]}",
    category: "{p["category"]}",
    basePrice: {p["basePrice"]},
    imageUrl: "{p["imageUrl"]}",
    supplier: "{p["supplier"]}",
    supplierModel: "{p["supplierModel"]}",
    supplierCost: {p["supplierCost"]},
    supplierProductId: "{p["supplierProductId"]}",
    tags: "{p["tags"]}",
    colors: [
      {colors_ts},
    ],
    sizes: [{sizes_ts}],
  }},
"""
    return products_ts

# Print the TS code
ts_code = generate_ts()
print(ts_code)
